"use client";

import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Locale = "en" | "bn";

type LanguageContextType = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  toggleLocale: () => void;
  t: (key: string) => string;
};

const STORAGE_KEY = "softune:dashboard-lang";

export const DICTIONARY: Record<Locale, Record<string, string>> = {
  en: {
    // Categories
    Overview: "Overview",
    Catalog: "Catalog",
    Sales: "Sales",
    Storefront: "Storefront",
    Settings: "Settings",
    "Getting Started": "Getting Started",
    "Super Admin": "Super Admin",

    // Menu Items
    Dashboard: "Dashboard",
    Analytics: "Analytics",
    Categories: "Categories",
    Products: "Products",
    Events: "Events",
    Orders: "Orders",
    "Store Sale": "Store Sale",
    Customers: "Customers",
    Dropship: "Dropship",
    "Browse Products": "Browse Products",
    "My Listings": "My Listings",
    Suppliers: "Suppliers",
    "Imported Products": "Imported Products",
    Settlements: "Settlements",
    Themes: "Themes",
    Courier: "Courier",
    Payments: "Payments",
    "Add-Ons": "Add-Ons",
    "Site Settings": "Site Settings",
    Domains: "Domains",
    SEO: "SEO",
    Shipping: "Shipping",
    "Contact Info": "Contact Info",
    "About Us": "About Us",
    FAQs: "FAQs",
    "Privacy Policy": "Privacy Policy",
    Terms: "Terms",
    Gallery: "Gallery",
    "Fraud Protection": "Fraud Protection",
    Billing: "Billing",
    Account: "Account",
    "Help Desk": "Help Desk",
    "Take a Tour": "Take a Tour",
    Logout: "Logout",
    Setup: "Setup",

    // User Menu & Header
    Accounts: "Accounts",
    "Switch site": "Switch site",
    "Quick access": "Quick access",
    "No domain yet": "No domain yet",
    "Open shop in a new tab": "Open shop in a new tab",
    "Log out": "Log out",

    // Dashboard & Overview
    "Total Orders": "Total Orders",
    "Pending Orders": "Pending Orders",
    "Total Customers": "Total Customers",
    "Total Revenue": "Total Revenue",
    "Sales Analysis": "Sales Analysis",
    "Last 6 Months": "Last 6 Months",
    "Last 30 Days": "Last 30 Days",
    "No sales yet": "No sales yet",
    "Revenue will chart here once orders start coming in.": "Revenue will chart here once orders start coming in.",
    "My Shop": "My Shop",
    Live: "Live",
    Draft: "Draft",
    "Your site": "Your site",
    storage: "storage",
    of: "of",
    Manage: "Manage",
    "Add product": "Add product",
    "Add category": "Add category",
    "Add Category": "Add Category",
    "Recent Orders": "Recent Orders",
    "Search orders...": "Search orders...",
    "Order ID": "Order ID",
    Date: "Date",
    Customer: "Customer",
    Items: "Items",
    Total: "Total",
    Status: "Status",
    "No orders match your search": "No orders match your search",
    "No site yet": "No site yet",
    "Create a site from a template in Themes to see store overview stats.": "Create a site from a template in Themes to see store overview stats.",
    "Create a site from a template in Themes to see analytics.": "Create a site from a template in Themes to see analytics.",
    "Couldn't load dashboard": "Couldn't load dashboard",
    "Couldn't load analytics": "Couldn't load analytics",
    "No orders yet": "No orders yet",
    "Recent storefront orders will appear here once customers start buying.": "Recent storefront orders will appear here once customers start buying.",
    "Last Month:": "Last Month:",
    "No data": "No data",

    // Analytics
    "Revenue Trend": "Revenue Trend",
    "Weekly sales performance curve": "Weekly sales performance curve",
    "Best Selling Categories": "Best Selling Categories",
    "Best Selling Products": "Best Selling Products",
    "Sales Report": "Sales Report",
    "Weekly breakdown with net sales": "Weekly breakdown with net sales",
    "Export CSV": "Export CSV",
    Export: "Export",
    "Avg. Order Value": "Avg. Order Value",
    "Refund Rate": "Refund Rate",
    Visitors: "Visitors",
    "Conversion Rate": "Conversion Rate",
    Profit: "Profit",
    "Profit is based on {pct}% of this period's revenue — set a Cost Price on more products for a fuller number.": "Profit is based on {pct}% of this period's revenue — set a Cost Price on more products for a fuller number.",
    "No sales in this period yet.": "No sales in this period yet.",
    sold: "sold",
    "CSV (Excel)": "CSV (Excel)",
    PDF: "PDF",
    JSON: "JSON",
    Period: "Period",
    Refunds: "Refunds",
    "Net Sales": "Net Sales",
    "No sales report data": "No sales report data",
    From: "From",
    To: "To",
    Last: "Last",
    Weeks: "Weeks",
    weeks: "weeks",

    // Order Statuses
    Pending: "Pending",
    Paid: "Paid",
    Fulfilled: "Fulfilled",
    Cancelled: "Cancelled",
    Refunded: "Refunded",

    // Months (short)
    Jan: "Jan",
    Feb: "Feb",
    Mar: "Mar",
    Apr: "Apr",
    May: "May",
    Jun: "Jun",
    Jul: "Jul",
    Aug: "Aug",
    Sep: "Sep",
    Oct: "Oct",
    Nov: "Nov",
    Dec: "Dec",

    // Catalog & Sales Sub-sections and common terms
    "Total Categories": "Total Categories",
    "Listed Products": "Listed Products",
    "All Categories": "All Categories",
    "Search categories...": "Search categories...",
    "Filter categories": "Filter categories",
    "Any product count": "Any product count",
    "Has products": "Has products",
    "No products": "No products",
    "Edit category": "Edit category",
    "New category": "New category",
    "Uploading images…": "Uploading images…",
    "Saving…": "Saving…",
    "Save changes": "Save changes",
    "Create category": "Create category",
    "Add banner": "Add banner",
    "Choose category icon": "Choose category icon",
    "Name": "Name",
    "Slug": "Slug",
    "Description": "Description",
    "e.g. Sarees": "e.g. Sarees",
    "auto-generated from name if left blank": "auto-generated from name if left blank",
    "Optional": "Optional",
    "Category created": "Category created",
    "Category updated": "Category updated",
    "Couldn't delete category": "Couldn't delete category",
    "Couldn't save changes": "Couldn't save changes",
    "Couldn't create category": "Couldn't create category",
    "Delete": "Delete",
    "You'll have 10 seconds to undo from the toast after this.": "You'll have 10 seconds to undo from the toast after this.",
    "No categories match your search or filters": "No categories match your search or filters",

    // Products
    "Total Products": "Total Products",
    "Out of Stock": "Out of Stock",
    "Inventory Value": "Inventory Value",
    "All Products": "All Products",
    "Search products...": "Search products...",
    "No products yet": "No products yet",
    "Add your first product to start selling.": "Add your first product to start selling.",
    "Couldn't load products": "Couldn't load products",
    "Couldn't delete product": "Couldn't delete product",
    "Filter products": "Filter products",
    "Product filters": "Product filters",
    "Clear all": "Clear all",
    "Category": "Category",
    "All categories": "All categories",
    "Uncategorized": "Uncategorized",
    "All stock levels": "All stock levels",
    "In stock": "In stock",
    "Unlimited": "Unlimited",
    "Edit product": "Edit product",
    "New product": "New product",
    "Product": "Product",
    "SKU": "SKU",
    "Price": "Price",
    "Stock": "Stock",
    "No products match your search or filters": "No products match your search or filters",
    "Edit": "Edit",
    "Edit Product": "Edit Product",
    "Add Product": "Add Product",
    "Save Product": "Save Product",
    "Product created": "Product created",
    "Product updated": "Product updated",
    "Couldn't create product": "Couldn't create product",
    "Couldn't load product": "Couldn't load product",
    "Details": "Details",
    "Product Title": "Product Title",
    "Price (৳)": "Price (৳)",
    "Compare-at (৳)": "Compare-at (৳)",
    "Cost Price (৳)": "Cost Price (৳)",
    "What this actually costs you — powers real profit in Analytics. Never shown to customers.": "What this actually costs you — powers real profit in Analytics. Never shown to customers.",
    "Short Description": "Short Description",
    "One or two sentences — used for SEO and search result snippets.": "One or two sentences — used for SEO and search result snippets.",
    "Video": "Video",
    "Product video": "Product video",
    "Variants": "Variants",
    "Feature highlights": "Feature highlights",
    "Organization": "Organization",
    "Inventory": "Inventory",
    "Product Serial": "Product Serial",
    "Unit": "Unit",
    "Initial Sold Count": "Initial Sold Count",
    "Free delivery": "Free delivery",
    "Delivery charge applies": "Delivery charge applies",
    "Delivery charges": "Delivery charges",
    "Pick every location this product can ship to. Add or edit locations in Site Settings → Shipping.": "Pick every location this product can ship to. Add or edit locations in Site Settings → Shipping.",
    "Pick every location this product can ship to.": "Pick every location this product can ship to.",
    "Add or edit locations in Site Settings → Shipping.": "Add or edit locations in Site Settings → Shipping.",
    "No delivery locations saved yet. Add some in Site Settings → Shipping, then come back here to pick which ones apply to this product.": "No delivery locations saved yet. Add some in Site Settings → Shipping, then come back here to pick which ones apply to this product.",
    "No delivery locations saved yet.": "No delivery locations saved yet.",
    "Add some in Site Settings → Shipping, then come back here to pick which ones apply to this product.": "Add some in Site Settings → Shipping, then come back here to pick which ones apply to this product.",
    "No variants yet. Add types like Size or Color.": "No variants yet. Add types like Size or Color.",
    "Add type": "Add type",
    "Variant name (e.g. Size, Color)": "Variant name (e.g. Size, Color)",
    "Color": "Color",
    "Priced": "Priced",
    "Add attribute (e.g. Large) + Enter": "Add attribute (e.g. Large) + Enter",
    "Add color name (e.g. Navy) + Enter": "Add color name (e.g. Navy) + Enter",

    // Events
    "Total Events": "Total Events",
    "Products in Events": "Products in Events",
    "All Events": "All Events",
    "Search events...": "Search events...",
    "No events yet": "No events yet",
    "Run a themed sale — New Arrival, Summer Sale — with a real discount on the products you pick.": "Run a themed sale — New Arrival, Summer Sale — with a real discount on the products you pick.",
    "Couldn't load events": "Couldn't load events",
    "Couldn't delete event": "Couldn't delete event",
    "Filter events": "Filter events",
    "Discount": "Discount",
    "off": "off",
    "Edit event": "Edit event",
    "New event": "New event",
    "Event": "Event",
    "Event created": "Event created",
    "Event updated": "Event updated",
    "No events match your search or filters": "No events match your search or filters",
    "Add Event": "Add Event",
    "Uploading image…": "Uploading image…",
    "Create event": "Create event",
    "Add event image": "Add event image",
    "A short line shown on the storefront card": "A short line shown on the storefront card",
    "Discount %": "Discount %",
    "Button label": "Button label",
    "Shop now": "Shop now",
    "Active — discount applies at checkout now": "Active — discount applies at checkout now",
    "Inactive — draft, no discount applied": "Inactive — draft, no discount applied",
    "Products in this event": "Products in this event",
    "selected": "selected",
    "No products yet — add from your catalog": "No products yet — add from your catalog",
    "No products match": "No products match",
    "Invalid discount": "Invalid discount",
    "Discount must be a whole number between 1 and 90.": "Discount must be a whole number between 1 and 90.",

    // Orders
    "Bulk book courier": "Bulk book courier",
    "Orders from your storefront checkout will show up here.": "Orders from your storefront checkout will show up here.",
    "Order Revenue": "Order Revenue",
    "Channel": "Channel",
    "In-Person": "In-Person",
    "Online": "Online",
    "All Orders": "All Orders",
    "Filter orders": "Filter orders",
    "All statuses": "All statuses",

    // Store Sale / POS
    "Cash": "Cash",
    "Card": "Card",
    "Mobile Banking": "Mobile Banking",
    "In-Person Sale": "In-Person Sale",
    "Cart": "Cart",
    "Walk-in Customer": "Walk-in Customer",
    "Complete Sale": "Complete Sale",
    "Sale Completed": "Sale Completed",
    "Print Receipt": "Print Receipt",
    "New Sale": "New Sale",

    // Customers
    "With Email": "With Email",
    "Phone Only": "Phone Only",
    "All Customers": "All Customers",
    "Search customers...": "Search customers...",
    "Customer Since": "Customer Since",
    "Contact": "Contact",
    "Any contact info": "Any contact info",
    "Has email": "Has email",
    "Filter customers": "Filter customers",
    "No customers yet": "No customers yet",
    "A customer record is created the first time someone checks out with a phone number — once your first order comes in, they'll appear here.": "A customer record is created the first time someone checks out with a phone number — once your first order comes in, they'll appear here.",
    "Couldn't load customers": "Couldn't load customers",
    "No customers match your search or filters": "No customers match your search or filters",

    // Dropship
    "Sections": "Sections",
    "All Suppliers": "All Suppliers",
    "Fulfillment Requests": "Fulfillment Requests",
    "Under Maintenance": "Under Maintenance",
    "Dropship is currently under maintenance. This feature will be available soon.": "Dropship is currently under maintenance. This feature will be available soon.",

    // Site Settings Common & Navigation
    "Custom domain": "Custom domain",
    "Custom domain saved": "Custom domain saved",
    "Custom domain removed": "Custom domain removed",
    "Couldn't save domain": "Couldn't save domain",
    "Now add the DNS record shown below.": "Now add the DNS record shown below.",
    "It'll connect once this site is published.": "It'll connect once this site is published.",
    "How to connect a domain": "How to connect a domain",
    "How to connect your domain": "How to connect your domain",
    "Free": "Free",
    "Custom": "Custom",
    "Not live yet": "Not live yet",
    "Connected": "Connected",
    "DNS not detected yet": "DNS not detected yet",
    "Unknown": "Unknown",

    // SEO
    "Site title": "Site title",
    "Title suffix": "Title suffix",
    "Meta description": "Meta description",
    "Keywords": "Keywords",
    "OG title": "OG title",
    "OG image": "OG image",
    "OG description": "OG description",
    "Indexing": "Indexing",
    "Sitemap": "Sitemap",
    "Google Analytics": "Google Analytics",
    "Search Console": "Search Console",
    "Facebook Pixel": "Facebook Pixel",
    "TikTok Pixel": "TikTok Pixel",
    "Google Tag Manager": "Google Tag Manager",
    "Favicon": "Favicon",
    "Meta Conversions API": "Meta Conversions API",
    "SEO settings saved": "SEO settings saved",
    "Couldn't save SEO settings": "Couldn't save SEO settings",
    "Save SEO": "Save SEO",
    "Allow": "Allow",
    "Hide": "Hide",
    "On": "On",
    "Off": "Off",

    // Shipping
    "Delivery locations": "Delivery locations",
    "Used in the Add Product page to pick a delivery charge instead of typing one each time.": "Used in the Add Product page to pick a delivery charge instead of typing one each time.",
    "Add location": "Add location",
    "No delivery locations yet. Add one to start pricing shipping by area.": "No delivery locations yet. Add one to start pricing shipping by area.",
    "Shipping settings saved": "Shipping settings saved",
    "Couldn't save shipping settings": "Couldn't save shipping settings",
    "Save shipping": "Save shipping",

    // Contact Info
    "Store contact": "Store contact",
    "Store display name": "Store display name",
    "Support email": "Support email",
    "Phone": "Phone",
    "WhatsApp": "WhatsApp",
    "Public store address": "Public store address",
    "Country": "Country",
    "City": "City",
    "Area / Thana": "Area / Thana",
    "Postal code": "Postal code",
    "Street address": "Street address",
    "Map link (optional)": "Map link (optional)",
    "Business hours": "Business hours",
    "Add hours": "Add hours",
    "Day": "Day",
    "Opens": "Opens",
    "Closes": "Closes",
    "Closed": "Closed",
    "Social media": "Social media",
    "Add link": "Add link",
    "Support note (shown on contact page)": "Support note (shown on contact page)",
    "Contact info saved": "Contact info saved",
    "Couldn't save contact info": "Couldn't save contact info",
    "Save contact info": "Save contact info",

    // About Us
    "Heading": "Heading",
    "About image": "About image",
    "Story paragraphs": "Story paragraphs",
    "Add paragraph": "Add paragraph",
    "Paragraph": "Paragraph",
    "About page saved": "About page saved",
    "Couldn't save the About page": "Couldn't save the About page",
    "Save About page": "Save About page",

    // FAQs
    "Questions": "Questions",
    "Add FAQ": "Add FAQ",
    "Question": "Question",
    "Answer": "Answer",
    "FAQs saved": "FAQs saved",
    "Couldn't save FAQs": "Couldn't save FAQs",
    "Save FAQs": "Save FAQs",

    // Legal (Privacy & Terms)
    "Page title": "Page title",
    "Policy content": "Policy content",
    "Terms content": "Terms content",
    "Published on storefront": "Published on storefront",
    "Privacy policy saved": "Privacy policy saved",
    "Couldn't save privacy policy": "Couldn't save privacy policy",
    "Save privacy policy": "Save privacy policy",
    "Terms saved": "Terms saved",
    "Couldn't save terms": "Couldn't save terms",
    "Save terms": "Save terms",

    // Gallery / Media
    "Images": "Images",
    Media: "Media",
    "First image is primary. Click another to make it primary. Uploaded when you save.": "First image is primary. Click another to make it primary. Uploaded when you save.",
    "JPEG, PNG, WebP, or AVIF · up to 10MB.": "JPEG, PNG, WebP, or AVIF · up to 10MB.",
    image: "image",
    images: "images",
    Primary: "Primary",
    "Upload": "Upload",
    "All": "All",
    "Other": "Other",
    "Delete selected": "Delete selected",
    "Upload media": "Upload media",
    "Drop images here or click to browse": "Drop images here or click to browse",
    "Replace image": "Replace image",
    "Add image": "Add image",

    // General Actions
    "Save": "Save",
    "Cancel": "Cancel",
    "Reset": "Reset",
  },
  bn: {
    // Categories
    Overview: "ওভারভিউ",
    Catalog: "ক্যাটালগ",
    Sales: "সেলস",
    Storefront: "স্টোরফ্রন্ট",
    Settings: "সেটিংস",
    "Getting Started": "গাইড",
    "Super Admin": "সুপার অ্যাডমিন",

    // Menu Items
    Dashboard: "ড্যাশবোর্ড",
    Analytics: "হিসাব-নিকাশ",
    Categories: "ক্যাটাগরি",
    Products: "প্রোডাক্ট",
    Events: "সেলস ক্যাম্পেইন",
    Orders: "অর্ডার",
    "Store Sale": "স্টোর সেল",
    Customers: "কাস্টমার",
    Dropship: "ড্রপশিপ",
    "Browse Products": "প্রোডাক্ট ব্রাউজ",
    "My Listings": "আমার লিস্টিং",
    Suppliers: "Suppliers",
    "Imported Products": "আমদানিকৃত প্রোডাক্ট",
    Settlements: "সেটেলমেন্ট",
    Themes: "থিম",
    Courier: "কুরিয়ার",
    Payments: "পেমেন্ট",
    "Add-Ons": "অ্যাড-অন",
    "Site Settings": "সাইট সেটিংস",
    Domains: "ডোমেইন",
    SEO: "SEO",
    Shipping: "শিপিং",
    "Contact Info": "যোগাযোগ তথ্য",
    "About Us": "আমাদের সম্পর্কে",
    FAQs: "FAQ",
    "Privacy Policy": "Privacy Policy",
    Terms: "Terms",
    Gallery: "গ্যালারি",
    "Fraud Protection": "ফ্রড প্রোটেকশন",
    Billing: "বিলিং",
    Account: "অ্যাকাউন্ট",
    "Help Desk": "হেল্প ডেস্ক",
    "Take a Tour": "ড্যাশবোর্ড ট্যুর",
    Logout: "লগআউট",
    Setup: "সেটআপ গাইড",

    // User Menu & Header
    Accounts: "অ্যাকাউন্ট",
    "Switch site": "সাইট পরিবর্তন",
    "Quick access": "কুইক অ্যাক্সেস",
    "No domain yet": "ডোমেইন যুক্ত করা হয়নি",
    "Open shop in a new tab": "নতুন ট্যাবে শপ দেখুন",
    "Log out": "লগআউট",

    // Dashboard & Overview
    "Total Orders": "মোট অর্ডার",
    "Pending Orders": "পেন্ডিং অর্ডার",
    "Total Customers": "মোট কাস্টমার",
    "Total Revenue": "মোট রেভিনিউ",
    "Sales Analysis": "সেলস অ্যানালাইসিস",
    "Last 6 Months": "গত ৬ মাস",
    "Last 30 Days": "গত ৩০ দিন",
    "No sales yet": "এখনো কোনো সেলস নেই",
    "Revenue will chart here once orders start coming in.": "অর্ডার আসা শুরু হলে রেভিনিউ চার্ট এখানে দেখা যাবে।",
    "My Shop": "আমার শপ",
    Live: "লাইভ",
    Draft: "ড্রাফট",
    "Your site": "আপনার সাইট",
    storage: "স্টোরেজ",
    of: "এর মধ্যে",
    Manage: "ম্যানেজ করুন",
    "Add product": "প্রোডাক্ট যুক্ত করুন",
    "Add category": "ক্যাটাগরি যুক্ত করুন",
    "Add Category": "ক্যাটাগরি যুক্ত করুন",
    "Recent Orders": "সাম্প্রতিক অর্ডারসমূহ",
    "Search orders...": "অর্ডার খুঁজুন...",
    "Order ID": "অর্ডার আইডি",
    Date: "তারিখ",
    Customer: "কাস্টমার",
    Items: "আইটেম",
    Total: "টোটাল",
    Status: "স্ট্যাটাস",
    "No orders match your search": "খোঁজা অর্ডারের সাথে কিছু মেলেনি",
    "No site yet": "এখনো কোনো সাইট নেই",
    "Create a site from a template in Themes to see store overview stats.": "স্টোরের ওভারভিউ পরিসংখ্যান দেখতে থিমস থেকে একটি টেমপ্লেট দিয়ে সাইট তৈরি করুন।",
    "Create a site from a template in Themes to see analytics.": "অ্যানালাইটিক্স দেখতে থিমস থেকে একটি টেমপ্লেট দিয়ে সাইট তৈরি করুন।",
    "Couldn't load dashboard": "ড্যাশবোর্ড লোড করা যায়নি",
    "Couldn't load analytics": "অ্যানালাইটিক্স লোড করা যায়নি",
    "No orders yet": "এখনো কোনো অর্ডার নেই",
    "Recent storefront orders will appear here once customers start buying.": "কাস্টমাররা কেনাকাটা শুরু করলে সাম্প্রতিক অর্ডারগুলো এখানে দেখা যাবে।",
    "Last Month:": "গত মাস:",
    "No data": "তথ্য নেই",

    // Analytics
    "Revenue Trend": "রেভিনিউ ট্রেন্ড",
    "Weekly sales performance curve": "সাপ্তাহিক সেলস পারফর্ম্যান্স কার্ভ",
    "Best Selling Categories": "সেরা বিক্রি হওয়া ক্যাটাগরি",
    "Best Selling Products": "সেরা বিক্রি হওয়া প্রোডাক্ট",
    "Sales Report": "সেলস রিপোর্ট",
    "Weekly breakdown with net sales": "নেট সেলসসহ সাপ্তাহিক হিসাব",
    "Export CSV": "CSV এক্সপোর্ট",
    Export: "এক্সপোর্ট",
    "Avg. Order Value": "গড় অর্ডার মূল্য",
    "Refund Rate": "রিফান্ড হার",
    Visitors: "ভিজিটর",
    "Conversion Rate": "কনভার্সন রেট",
    Profit: "প্রফিট",
    "Profit is based on {pct}% of this period's revenue — set a Cost Price on more products for a fuller number.": "প্রফিট {pct}% রেভিনিউ হিসাবের ওপর ভিত্তি করে তৈরি — আরও সঠিক হিসাব পেতে প্রোডাক্টের কস্ট প্রাইস সেট করুন।",
    "No sales in this period yet.": "এই সময়ে কোনো বিক্রি হয়নি।",
    sold: "বিক্রি",
    "CSV (Excel)": "CSV (এক্সেল)",
    PDF: "PDF",
    JSON: "JSON",
    Period: "সময়কাল",
    Refunds: "রিফান্ড",
    "Net Sales": "নেট সেলস",
    "No sales report data": "কোনো সেলস রিপোর্ট তথ্য নেই",
    From: "শুরু",
    To: "শেষ",
    Last: "গত",
    Weeks: "সপ্তাহ",
    weeks: "সপ্তাহ",

    // Order Statuses
    Pending: "পেন্ডিং",
    Paid: "পেইড",
    Fulfilled: "ডেলিভার্ড",
    Cancelled: "বাতিল",
    Refunded: "রিফান্ড করা হয়েছে",

    // Months (short)
    Jan: "জানু",
    Feb: "ফেব্রু",
    Mar: "মার্চ",
    Apr: "এপ্রিল",
    May: "মে",
    Jun: "জুন",
    Jul: "জুলাই",
    Aug: "আগস্ট",
    Sep: "সেপ্টে",
    Oct: "অক্টো",
    Nov: "নভে",
    Dec: "ডিসে",

    // Catalog & Sales Sub-sections and common terms
    "Total Categories": "মোট ক্যাটাগরি",
    "Listed Products": "তালিকাবদ্ধ প্রোডাক্ট",
    "All Categories": "সকল ক্যাটাগরি",
    "Search categories...": "ক্যাটাগরি খুঁজুন...",
    "Filter categories": "ক্যাটাগরি ফিল্টার",
    "Any product count": "যেকোনো পরিমাণ প্রোডাক্ট",
    "Has products": "প্রোডাক্ট আছে",
    "No products": "কোনো প্রোডাক্ট নেই",
    "Edit category": "ক্যাটাগরি এডিট করুন",
    "New category": "নতুন ক্যাটাগরি",
    "Uploading images…": "ছবি আপলোড হচ্ছে…",
    "Saving…": "সংরক্ষণ করা হচ্ছে…",
    "Save changes": "পরিবর্তন সংরক্ষণ করুন",
    "Create category": "ক্যাটাগরি তৈরি করুন",
    "Add banner": "ব্যানার যুক্ত করুন",
    "Choose category icon": "আইকন বেছে নিন",
    "Name": "নাম",
    "Slug": "স্লাগ",
    "Description": "বিবরণ",
    "e.g. Sarees": "যেমন: শাড়ি",
    "auto-generated from name if left blank": "ফাঁকা রাখলে নাম থেকে স্বয়ংক্রিয়ভাবে তৈরি হবে",
    "Optional": "ঐচ্ছিক",
    "Category created": "ক্যাটাগরি তৈরি হয়েছে",
    "Category updated": "ক্যাটাগরি আপডেট হয়েছে",
    "Couldn't delete category": "ক্যাটাগরি ডিলিট করা যায়নি",
    "Couldn't save changes": "পরিবর্তন সংরক্ষণ করা যায়নি",
    "Couldn't create category": "ক্যাটাগরি তৈরি করা যায়নি",
    "Delete": "ডিলিট করুন",
    "You'll have 10 seconds to undo from the toast after this.": "পরবর্তী ১০ সেকেন্ডের মধ্যে টোস্ট থেকে আন্ডু করতে পারবেন.",
    "No categories match your search or filters": "খোঁজা তথ্যের সাথে কোনো ক্যাটাগরি মেলেনি",

    // Products
    "Total Products": "মোট প্রোডাক্ট",
    "Out of Stock": "স্টক শেষ",
    "Inventory Value": "ইনভেন্টরি মান",
    "All Products": "সকল প্রোডাক্ট",
    "Search products...": "প্রোডাক্ট খুঁজুন...",
    "No products yet": "এখনো কোনো প্রোডাক্ট নেই",
    "Add your first product to start selling.": "বিক্রি শুরু করতে আপনার প্রথম প্রোডাক্ট যুক্ত করুন।",
    "Couldn't load products": "প্রোডাক্ট লোড করা যায়নি",
    "Couldn't delete product": "প্রোডাক্ট ডিলিট করা যায়নি",
    "Filter products": "প্রোডাক্ট ফিল্টার",
    "Product filters": "প্রোডাক্ট ফিল্টারসমূহ",
    "Clear all": "ক্লিয়ার অল",
    "Category": "ক্যাটাগরি",
    "All categories": "সকল ক্যাটাগরি",
    "Uncategorized": "ক্যাটাগরি ছাড়া",
    "All stock levels": "সকল স্টক লেভেল",
    "In stock": "স্টকে আছে",
    "Unlimited": "সীমাহীন",
    "Edit product": "প্রোডাক্ট এডিট করুন",
    "New product": "নতুন প্রোডাক্ট",
    "Product": "প্রোডাক্ট",
    "SKU": "SKU",
    "Price": "মূল্য",
    "Stock": "স্টক",
    "No products match your search or filters": "খোঁজা তথ্যের সাথে কোনো প্রোডাক্ট মেলেনি",
    "Edit": "সম্পাদনা",
    "Edit Product": "প্রোডাক্ট এডিট করুন",
    "Add Product": "প্রোডাক্ট যুক্ত করুন",
    "Save Product": "প্রোডাক্ট সেভ করুন",
    "Product created": "প্রোডাক্ট তৈরি হয়েছে",
    "Product updated": "প্রোডাক্ট আপডেট হয়েছে",
    "Couldn't create product": "প্রোডাক্ট তৈরি করা যায়নি",
    "Couldn't load product": "প্রোডাক্ট লোড করা যায়নি",
    "Details": "বিস্তারিত বিবরণ",
    "Product Title": "প্রোডাক্টের নাম",
    "Price (৳)": "মূল্য (৳)",
    "Compare-at (৳)": "আগের মূল্য (৳)",
    "Cost Price (৳)": "কেনা দাম/খরচ (৳)",
    "What this actually costs you — powers real profit in Analytics. Never shown to customers.": "পণ্যটির আসল কেনা দাম/খরচ — যা অ্যানালিটিক্সে সঠিক লাভ হিসাব করতে সাহায্য করে। গ্রাহকদের কখনো দেখানো হয় না।",
    "Short Description": "সংক্ষিপ্ত বিবরণ",
    "One or two sentences — used for SEO and search result snippets.": "এক বা দুই বাক্য — এসইও (SEO) এবং সার্চ রেজাল্ট স্নিপেটের জন্য ব্যবহৃত হবে।",
    "Video": "ভিডিও",
    "Product video": "প্রোডাক্ট ভিডিও",
    "Variants": "ভেরিয়েন্টসমূহ",
    "Feature highlights": "হাইলাইট বৈশিষ্ট্যসমূহ",
    "Organization": "ক্যাটাগরি ও স্টেটাস",
    "Inventory": "ইনভেন্টরি / স্টক",
    "Product Serial": "প্রোডাক্ট সিরিয়াল",
    "Unit": "একক (Unit)",
    "Initial Sold Count": "শুরুতে দেখানো বিক্রি সংখ্যা",
    "Free delivery": "ফ্রি ডেলিভারি",
    "Delivery charge applies": "ডেলিভারি চার্জ প্রযোজ্য",
    "Delivery charges": "ডেলিভারি চার্জসমূহ",
    "Pick every location this product can ship to. Add or edit locations in Site Settings → Shipping.": "পণ্যটি যেসব জায়গায় ডেলিভারি দেওয়া যাবে সেগুলো নির্বাচন করুন। লোকেশন যোগ বা এডিট করতে সাইট সেটিংস → শিপিং-এ যান।",
    "Pick every location this product can ship to.": "পণ্যটি যেসব জায়গায় ডেলিভারি দেওয়া যাবে সেগুলো নির্বাচন করুন।",
    "Add or edit locations in Site Settings → Shipping.": "লোকেশন যোগ বা এডিট করতে সাইট সেটিংস → শিপিং-এ যান।",
    "No delivery locations saved yet. Add some in Site Settings → Shipping, then come back here to pick which ones apply to this product.": "এখনও কোনো ডেলিভারি লোকেশন যুক্ত করা হয়নি। সাইট সেটিংস → শিপিং থেকে লোকেশন যুক্ত করুন, তারপর এই পণ্যে নির্বাচন করুন।",
    "No delivery locations saved yet.": "এখনও কোনো ডেলিভারি লোকেশন যুক্ত করা হয়নি।",
    "Add some in Site Settings → Shipping, then come back here to pick which ones apply to this product.": "সাইট সেটিংস → শিপিং থেকে লোকেশন যুক্ত করুন, তারপর এই পণ্যে নির্বাচন করুন।",
    "No variants yet. Add types like Size or Color.": "এখনো কোনো ভেরিয়েন্ট নেই। সাইজ বা কালারের মতো টাইপ যুক্ত করুন।",
    "Add type": "টাইপ যুক্ত করুন",
    "Variant name (e.g. Size, Color)": "ভেরিয়েন্টের নাম (যেমন: সাইজ, কালার)",
    "Color": "কালার",
    "Priced": "দাম পরিবর্তনশীল",
    "Add attribute (e.g. Large) + Enter": "অ্যাট্রিবিউট লিখুন (যেমন: L) + এন্টার চাপুন",
    "Add color name (e.g. Navy) + Enter": "কালারের নাম লিখুন (যেমন: নেভি) + এন্টার চাপুন",

    // Events
    "Total Events": "মোট ক্যাম্পেইন",
    "Products in Events": "ক্যাম্পেইনে প্রোডাক্ট",
    "All Events": "সকল ক্যাম্পেইন",
    "Search events...": "ক্যাম্পেইন খুঁজুন...",
    "No events yet": "এখনো কোনো সেলস ক্যাম্পেইন নেই",
    "Run a themed sale — New Arrival, Summer Sale — with a real discount on the products you pick.": "নির্দিষ্ট প্রোডাক্ট ছাড় দিয়ে স্পেশাল সেলস ক্যাম্পেইন চালান।",
    "Couldn't load events": "ক্যাম্পেইন লোড করা যায়নি",
    "Couldn't delete event": "ক্যাম্পেইন ডিলিট করা যায়নি",
    "Filter events": "ক্যাম্পেইন ফিল্টার",
    "Discount": "ছাড়",
    "off": "ছাড়",
    "Edit event": "ক্যাম্পেইন এডিট করুন",
    "New event": "নতুন ক্যাম্পেইন",
    "Event": "ক্যাম্পেইন",
    "Event created": "ক্যাম্পেইন তৈরি হয়েছে",
    "Event updated": "ক্যাম্পেইন আপডেট হয়েছে",
    "No events match your search or filters": "খোঁজা তথ্যের সাথে কোনো ক্যাম্পেইন মেলেনি",
    "Add Event": "ক্যাম্পেইন যুক্ত করুন",
    "Add event image": "ক্যাম্পেইনের ছবি যুক্ত করুন",
    "A short line shown on the storefront card": "স্টোরফ্রন্ট কার্ডে দেখানোর ছোট বিবরণ",
    "Discount %": "ছাড়ের শতাংশ (%)",
    "Button label": "বাটনের লেখা",
    "Shop now": "এখনই কিনুন",
    "Active — discount applies at checkout now": "সক্রিয় — চেকআউটে ছাড় প্রযোজ্য হবে",
    "Inactive — draft, no discount applied": "নিষ্ক্রিয় — ড্রাফট, কোনো ছাড় প্রযোজ্য নয়",
    "Products in this event": "ক্যাম্পেইনের প্রোডাক্টসমূহ",
    "selected": "টি নির্বাচিত",
    "No products yet — add from your catalog": "এখনো কোনো প্রোডাক্ট নেই — ক্যাটালগ থেকে যুক্ত করুন",
    "No products match": "কোনো প্রোডাক্ট মেলেনি",
    "Invalid discount": "অকার্যকর ছাড়",
    "Discount must be a whole number between 1 and 90.": "ছাড়ের পরিমাণ ১ থেকে ৯০ এর মধ্যে পূর্ণসংখ্যা হতে হবে।",

    // Orders
    "Bulk book courier": "বাল্ক কুরিয়ার বুকিং",
    "Orders from your storefront checkout will show up here.": "কাস্টমারের দেওয়া নতুন অর্ডারসমূহ এখানে দেখা যাবে।",
    "Order Revenue": "অর্ডার রেভিনিউ",
    "Channel": "চ্যানেল",
    "In-Person": "সরাসরি বিক্রি",
    "Online": "অনলাইন",
    "All Orders": "সকল অর্ডার",
    "Filter orders": "অর্ডার ফিল্টার",
    "All statuses": "সকল স্ট্যাটাস",

    // Store Sale / POS
    "Cash": "ক্যাশ",
    "Card": "কার্ড",
    "Mobile Banking": "মোবাইল ব্যাংকিং",
    "In-Person Sale": "স্টোর সেল",
    "Cart": "কার্ট",
    "Walk-in Customer": "কাউন্টার কাস্টমার",
    "Complete Sale": "বিক্রি সম্পন্ন করুন",
    "Sale Completed": "বিক্রি সম্পন্ন হয়েছে",
    "Print Receipt": "রসিদ প্রিন্ট করুন",
    "New Sale": "নতুন বিক্রি",

    // Customers
    "With Email": "ইমেইলসহ",
    "Phone Only": "শুধু ফোন নম্বর",
    "All Customers": "সকল কাস্টমার",
    "Search customers...": "কাস্টমার খুঁজুন...",
    "Customer Since": "কাস্টমার যুক্ত হওয়ার তারিখ",
    "Contact": "যোগাযোগ",
    "Any contact info": "যেকোনো যোগাযোগ তথ্য",
    "Has email": "ইমেইল আছে",
    "Filter customers": "কাস্টমার ফিল্টার",
    "No customers yet": "এখনো কোনো কাস্টমার নেই",
    "A customer record is created the first time someone checks out with a phone number — once your first order comes in, they'll appear here.": "প্রথম অর্ডার পাওয়ার সাথে সাথেই কাস্টমারের তথ্য এখানে দেখা যাবে।",
    "Couldn't load customers": "কাস্টমার লোড করা যায়নি",
    "No customers match your search or filters": "খোঁজা তথ্যের সাথে কোনো কাস্টমার মেলেনি",

    // Dropship
    "Sections": "বিভাগসমূহ",
    "All Suppliers": "All Suppliers",
    "Fulfillment Requests": "ফুলফিলমেন্ট রিকোয়েস্ট",
    "Under Maintenance": "আন্ডার মেইনটেন্যান্স",
    "Dropship is currently under maintenance. This feature will be available soon.": "ড্রপশিপ এখন মেইনটেন্যান্সে রয়েছে। খুব শীঘ্রই এই ফিচারটি এভেলেবল হবে।",

    // Site Settings Common & Navigation
    "Custom domain": "কাস্টম ডোমেইন",
    "Custom domain saved": "কাস্টম ডোমেইন সংরক্ষিত হয়েছে",
    "Custom domain removed": "কাস্টম ডোমেইন মুছে ফেলা হয়েছে",
    "Couldn't save domain": "ডোমেইন সংরক্ষণ করা যায়নি",
    "Now add the DNS record shown below.": "নিচে দেখানো DNS রেকর্ড যোগ করুন।",
    "It'll connect once this site is published.": "সাইট পাবলিশ হলে এটি কানেক্ট হবে।",
    "How to connect a domain": "যেভাবে ডোমেইন কানেক্ট করবেন",
    "How to connect your domain": "যেভাবে আপনার ডোমেইন কানেক্ট করবেন",
    "Free": "ফ্রি",
    "Custom": "কাস্টম",
    "Not live yet": "এখনো লাইভ হয়নি",
    "Connected": "কানেক্টেড",
    "DNS not detected yet": "DNS এখনো পাওয়া যায়নি",
    "Unknown": "অজানা",

    // SEO
    "Site title": "সাইট টাইটেল",
    "Title suffix": "টাইটেল সাফিক্স",
    "Meta description": "মেটা ডেসক্রিপশন",
    "Keywords": "কীওয়ার্ডসমূহ",
    "OG title": "OG টাইটেল",
    "OG image": "OG ইমেজ",
    "OG description": "OG ডেসক্রিপশন",
    "Indexing": "ইনডেক্সিং",
    "Sitemap": "সাইটম্যাপ",
    "Google Analytics": "Google Analytics",
    "Search Console": "Search Console",
    "Facebook Pixel": "Facebook Pixel",
    "TikTok Pixel": "TikTok Pixel",
    "Google Tag Manager": "Google Tag Manager",
    "Favicon": "ফেভিকন",
    "Meta Conversions API": "Meta Conversions API",
    "SEO settings saved": "SEO সেটিংস সংরক্ষণ করা হয়েছে",
    "Couldn't save SEO settings": "SEO সেটিংস সংরক্ষণ করা যায়নি",
    "Save SEO": "SEO সেভ করুন",
    "Allow": "অনুমতি দিন",
    "Hide": "লুকিয়ে রাখুন",
    "On": "অন",
    "Off": "অফ",

    // Shipping
    "Delivery locations": "ডেলিভারি লোকেশনসমূহ",
    "Used in the Add Product page to pick a delivery charge instead of typing one each time.": "প্রোডাক্ট যুক্ত করার পেজে প্রতিবার নতুন করে লেখার বদলে ডেলিভারি চার্জ বেছে নিতে ব্যবহ‌ৃত হয়।",
    "Add location": "লোকেশন যুক্ত করুন",
    "No delivery locations yet. Add one to start pricing shipping by area.": "এখনো কোনো ডেলিভারি লোকেশন নেই। এলাকাভিত্তিক শিপিং চার্জ সেট করতে একটি যুক্ত করুন।",
    "Shipping settings saved": "শিপিং সেটিংস সংরক্ষিত হয়েছে",
    "Couldn't save shipping settings": "শিপিং সেটিংস সংরক্ষণ করা যায়নি",
    "Save shipping": "শিপিং সেভ করুন",

    // Contact Info
    "Store contact": "স্টোর যোগাযোগ",
    "Store display name": "স্টোরের প্রদর্শিত নাম",
    "Support email": "সাপোর্ট ইমেইল",
    "Phone": "ফোন নম্বর",
    "WhatsApp": "হোয়াটসঅ্যাপ",
    "Public store address": "স্টোরের ঠিকানা",
    "Country": "দেশ",
    "City": "শহর",
    "Area / Thana": "এলাকা / থানা",
    "Postal code": "পোস্টাল কোড",
    "Street address": "রাস্তা / বিস্তারিত ঠিকানা",
    "Map link (optional)": "ম্যাপ লিংক (ঐচ্ছিক)",
    "Business hours": "খোলা থাকার সময়সূচী",
    "Add hours": "সময়সূচী যুক্ত করুন",
    "Day": "দিন",
    "Opens": "খোলে",
    "Closes": "বন্ধ হয়",
    "Closed": "বন্ধ",
    "Social media": "সোশ্যাল মিডিয়া",
    "Add link": "লিংক যুক্ত করুন",
    "Support note (shown on contact page)": "সাপোর্ট নোট (যোগাযোগ পেজে দেখানো হবে)",
    "Contact info saved": "যোগাযোগ তথ্য সংরক্ষণ করা হয়েছে",
    "Couldn't save contact info": "যোগাযোগ তথ্য সংরক্ষণ করা যায়নি",
    "Save contact info": "যোগাযোগ তথ্য সেভ করুন",

    // About Us
    "Heading": "শিরোনাম",
    "About image": "আমাদের সম্পর্কে ছবি",
    "Story paragraphs": "গল্পের বিবরণসমূহ",
    "Add paragraph": "প্যারাগ্রাফ যুক্ত করুন",
    "Paragraph": "প্যারাগ্রাফ",
    "About page saved": "আমাদের সম্পর্কে পেজটি সংরক্ষণ করা হয়েছে",
    "Couldn't save the About page": "আমাদের সম্পর্কে পেজটি সংরক্ষণ করা যায়নি",
    "Save About page": "আমাদের সম্পর্কে পেজ সেভ করুন",

    // FAQs
    "Questions": "প্রশ্নসমূহ",
    "Add FAQ": "FAQ যুক্ত করুন",
    "Question": "প্রশ্ন",
    "Answer": "উত্তর",
    "FAQs saved": "FAQ সংরক্ষণ করা হয়েছে",
    "Couldn't save FAQs": "FAQ সংরক্ষণ করা যায়নি",
    "Save FAQs": "FAQ সেভ করুন",

    // Legal (Privacy & Terms)
    "Page title": "পেজ টাইটেল",
    "Policy content": "পলিসি বিবরণ",
    "Terms content": "টার্মস বিবরণ",
    "Published on storefront": "স্টোরফ্রন্টে প্রকাশিত",
    "Privacy policy saved": "Privacy Policy সংরক্ষণ করা হয়েছে",
    "Couldn't save privacy policy": "Privacy Policy সংরক্ষণ করা যায়নি",
    "Save privacy policy": "Privacy Policy সেভ করুন",
    "Terms saved": "Terms সংরক্ষণ করা হয়েছে",
    "Couldn't save terms": "Terms সংরক্ষণ করা যায়নি",
    "Save terms": "Terms সেভ করুন",

    // Gallery / Media
    "Images": "ছবিসমূহ",
    Media: "মিডিয়া",
    "First image is primary. Click another to make it primary. Uploaded when you save.": "প্রথম ছবিটি মূল ছবি হিসেবে থাকবে। অন্য ছবিকে মূল করতে সেটিতে ক্লিক করুন। সেভ করার পর আপলোড হবে।",
    "JPEG, PNG, WebP, or AVIF · up to 10MB.": "JPEG, PNG, WebP, অথবা AVIF · ১০MB পর্যন্ত।",
    image: "ছবি",
    images: "ছবি",
    Primary: "মূল ছবি",
    "Upload": "আপলোড",
    "All": "সব",
    "Other": "অন্যান্য",
    "Delete selected": "বাছাইকৃতগুলো মুছুন",
    "Upload media": "মিডিয়া আপলোড করুন",
    "Drop images here or click to browse": "ছবি এখানে ড্রপ করুন অথবা ব্রাউজ করতে ক্লিক করুন",
    "Replace image": "ছবি পরিবর্তন করুন",
    "Add image": "ছবি যুক্ত করুন",

    // General Actions
    "Save": "সংরক্ষণ",
    "Cancel": "বাতিল",
    "Reset": "রিসেট",

    // Fraud Protection (Casual Bangla)
    "Protection rules": "সুরক্ষা নিয়মাবলী",
    "Suspicious orders": "সন্দেহজনক অর্ডার",
    "Numbers blocked": "ব্লক করা নম্বর",
    "IPs blocked": "ব্লক করা IP",
    "Rules active": "সক্রিয় নিয়ম",
    "Checkout rules": "চেকআউট রুলস",
    "Changes stay local until you hit Save.": "সেভ না করা পর্যন্ত পরিবর্তনগুলো লোকাল থাকবে।",
    "Hold first-time high-value orders": "নতুন কাস্টমারের বড় অর্ডার আটকে রাখুন",
    "First-time customers with an order over this amount wait for your review.": "নতুন কোনো কাস্টমার নির্দিষ্ট টাকার চেয়ে বেশি অর্ডার করলে রিভিউ এর জন্য জমা থাকবে।",
    "Order value over": "অর্ডার অ্যামাউন্ট বেশি",
    "Flag burst orders from one phone": "একই নম্বর থেকে ঘনঘন অর্ডার ফ্ল্যাগ করুন",
    "If the same phone places 2+ orders inside this window, flag for review.": "একই ফোন নম্বর থেকে অল্প সময়ে একাধিক অর্ডার আসলে রিভিউ এর জন্য ফ্ল্যাগ হবে।",
    "Within": "সময় সীমা",
    "min": "মিনিট",
    "Block blocklisted numbers": "ব্লকলিস্টের নম্বরগুলো ব্লক করুন",
    "Reject checkout from any phone on your blocklist below.": "নিচের ব্লকলিস্টে থাকা নম্বরগুলো চেকআউট করতে পারবে না।",
    "One open order per device": "এক ডিভাইস থেকে একটি অর্ডার",
    "A device can't place a new order while it already has one in progress at your store.": "একটি ডিভাইস থেকে অর্ডারের কাজ চলাকালীন নতুন কোনো অর্ডার দেওয়া যাবে না।",
    "Cooldown after a cancelled order": "অর্ডার বাতিলের পর কুলডাউন",
    "After a cancelled or confirmed-fraud order, block new orders from that device for a while.": "অর্ডার ক্যানসেল বা ফ্রড প্রমাণিত হলে কিছুক্ষণের জন্য ওই ডিভাইস থেকে অর্ডার দেওয়া বন্ধ থাকবে।",
    "Cooldown for": "কুলডাউন সময়",
    "Blocklist": "ব্লকলিস্ট",
    "Add or remove numbers freely — Save writes the list.": "প্রয়োজনমতো নম্বর যোগ বা মুছুন — সেভ করলেই লিস্ট তৈরি হয়ে যাবে।",
    "Add number": "নম্বর যোগ করুন",
    "No numbers blocked": "কোনো নম্বর ব্লক করা নেই",
    "Add phones you already know are bad — from experience or word of mouth.": "যেসব ভুয়া বা ক্ষতিকর নম্বর আপনার জানা আছে সেগুলো ব্লকলিস্টে যোগ করুন।",
    "Add first number": "প্রথম নম্বরটি যোগ করুন",
    "IP blocklist": "IP ব্লকলিস্ট",
    "Blocks browsing entirely, not just checkout — Save writes the list.": "ওয়েবসাইট ব্রাউজ করা পুরোপুরি ব্লক করবে — সেভ করলেই লিস্ট সেভ হবে।",
    "Add IP": "IP যোগ করুন",
    "No IPs blocked": "কোনো IP ব্লক করা নেই",
    "Block an address that's spamming or attacking your storefront — it won't be able to load any page, not just checkout.": "স্প্যাম বা ক্ষতি করার চেষ্টা করা IP এড্রেস ব্লক করুন — তারা ওয়েবসাইট দেখতে পারবে না।",
    "Add first IP": "প্রথম IP যোগ করুন",
    "Remove from list?": "লিস্ট থেকে মুছে ফেলবেন?",
    "Block a number": "একটি নম্বর ব্লক করুন",
    "Phone number": "ফোন নম্বর",
    "Note": "নোট",
    "Optional — why blocked": "ঐচ্ছিক — কেন ব্লক করা হলো",
    "Block an IP address": "একটি IP এড্রেস ব্লক করুন",
    "IP address": "IP এড্রেস",
    "Exact address only — ranges (CIDR) aren't supported.": "নির্দিষ্ট IP এড্রেস লিখুন — কোনো রেঞ্জ ব্যবহার করা যাবে না।",
    "No suspicious orders": "কোনো সন্দেহজনক অর্ডার নেই",
    "Orders flagged by your checkout rules (high-value first orders, order bursts) show up here for review.": "বড় অর্ডার বা ঘনঘন দেওয়া অর্ডার রিভিউর জন্য এখানে জমা হবে।",
    "Flagged for review — clearing or confirming takes effect immediately.": "রিভিউর জন্য রাখা হয়েছে — এপ্রুভ বা ফ্রড কনফার্ম সঙ্গে সঙ্গেই কার্যকর হবে।",
    "High-value first order": "নতুন কাস্টমারের বড় অর্ডার",
    "Burst of orders": "একসাথে অনেকগুলো অর্ডার",
    "Flagged": "ফ্ল্যাগ করা হয়েছে",
    "Clear": "ক্লিয়ার করুন",
    "Mark fraud": "ফ্রড চিহ্নিত করুন",
    "Block IP": "IP ব্লক করুন",
    "IP blocked": "IP ব্লক করা হয়েছে",
    "No note": "কোনো নোট নেই",

    // Billing (Casual Bangla)
    "Current plan": "বর্তমান প্ল্যান",
    "Active": "সক্রিয়",
    "Trial": "ট্রায়াল",
    "Assigned by the Softunebd team": "Softunebd টিম থেকে দেওয়া হয়েছে",
    "1 store": "১টি স্টোর",
    "Latest invoice": "সর্বশেষ ইনভয়েস",
    "No billing — trial access": "বিলিং নেই — ফ্রি ট্রায়াল সুবিধা",
    "Billed monthly, applied manually by our team": "মাসিক বিলিং, আমাদের টিম ম্যানুয়ালি সেট করে দেয়",
    "Upgrade plan": "প্ল্যান আপগ্রেড করুন",
    "Upgrade from trial": "ট্রায়াল থেকে আপগ্রেড করুন",
    "Contact support to cancel": "বাতিল করতে সাপোর্টে কথা বলুন",
    "Plans": "সকল প্ল্যান",
    "Popular": "জনপ্রিয়",
    "Billing history": "বিলিং হিস্ট্রি",
    "Invoices and past subscription charges": "ইনভয়েস এবং পূর্ববর্তী খরচের হিসাব",
    "No invoices yet": "এখনো কোনো ইনভয়েস নেই",
    "An invoice shows up here once your trial starts or your plan changes.": "ট্রায়াল শুরু হলে বা প্ল্যান পাল্টালে এখানে ইনভয়েস দেখতে পাবেন।",
    "Switch to": "সুইচ করুন",
    "Email sales": "সেলসে ইমেইল করুন",
    "Current plan name": "বর্তমান প্ল্যান",

    // Account (Casual Bangla)
    "Role": "ভূমিকা",
    "Store": "স্টোর",
    "Joined": "যোগদানের তারিখ",
    "Change profile picture": "প্রোফাইল ছবি পরিবর্তন করুন",
    "Profile details": "প্রোফাইল তথ্য",
    "Full name": "পুরো নাম",
    "Email": "ইমেইল",
    "Timezone": "টাইমজোন",
    "Contact support to change your login email.": "লগইন ইমেইল পরিবর্তন করতে সাপোর্টে যোগাযোগ করুন।",
    "Save profile": "প্রোফাইল সেভ করুন",
    "Business details": "বিজনেসের বিবরণ",
    "Legal business name": "আইনি ব্যবসার নাম",
    "Trade / brand name": "ট্রেড / ব্র্যান্ডের নাম",
    "Business type": "ব্যবসার ধরন",
    "Trade license no.": "ট্রেড লাইসেন্স নম্বর",
    "TIN / VAT": "TIN / VAT",
    "Billing email": "বিলিং ইমেইল",
    "Save business details": "বিজনেসের তথ্য সেভ করুন",
    "Security": "সিকিউরিটি",
    "Password": "পাসওয়ার্ড",
    "A code emailed to you is required to change it.": "পাসওয়ার্ড পাল্টাতে আপনার ইমেইলে একটি সিকিউরিটি কোড যাবে।",
    "Change password": "পাসওয়ার্ড পরিবর্তন করুন",
    "Two-Factor Authentication (2FA)": "টু-ফ্যাক্টর অথেন্টিকেশন (2FA)",
    "Add an extra layer of security to your account.": "আপনার একাউন্টে বাড়তি সিকিউরিটি যুক্ত করুন।",
    "Coming soon": "শীঘ্রই আসছে",
    "Notifications": "নোটিফিকেশন",
    "New orders": "নতুন অর্ডার",
    "Email when a customer places an order": "কাস্টমার অর্ডার করলে ইমেইলে অ্যালার্ট পান",
    "Low stock alerts": "স্টক কমে যাওয়ার অ্যালার্ট",
    "Notify when product stock is low": "প্রোডাক্টের স্টক কমে গেলে নোটিফিকেশন পান",
    "Billing & invoices": "বিলিং ও ইনভয়েস",
    "Subscription renewals and payment receipts": "সাবস্ক্রিপশন ও পেমেন্ট রিসিট সংক্রান্ত তথ্য",
    "Product tips": "প্রোডাক্ট টিপস",
    "Occasional Softunebd product updates": "Softunebd এর নতুন আপডেট ও সহায়িকা",
    "Save preferences": "পছন্দসমূহ সেভ করুন",

    // Help Desk (Casual Bangla)
    "Open tickets": "ওপেন টিকেট",
    "In progress": "চলমান",
    "Resolved": "সমাধান হয়েছে",
    "Quick help": "দ্রুত সাহায্য",
    "Popular guides": "জনপ্রিয় গাইডসমূহ",
    "New ticket": "নতুন টিকেট",
    "Tell us what you need help with": "আপনার কী সাহায্য লাগবে জানান",
    "Subject": "বিষয়",
    "Priority": "গুরুত্ব",
    "Message": "মেসেজ",
    "Brief summary of the issue": "সমস্যার একটি ছোট বিবরণ",
    "Describe the problem with steps if you can…": "সমস্যাটি একটু বিস্তারিত লিখুন…",
    "Submit ticket": "টিকেট সাবমিট করুন",
    "Your tickets": "আপনার টিকেটসমূহ",
    "Search tickets...": "টিকেট খুঁজুন...",
    "No tickets yet — submit one above and it'll show up here.": "এখনো কোনো টিকেট নেই — ওপরে নতুন টিকেট খুললে এখানে জমা হবে।",
    "Ticket": "টিকেট",
    "Updated": "সর্বশেষ আপডেট",
    "Submitted": "জমাদানের তারিখ",
    "Last updated": "সর্বশেষ আপডেট",
    "Your message": "আপনার মেসেজ",
    "We'll follow up by email — replies aren't shown here yet.": "ইমেইলের মাধ্যমে আপডেট জানানো হবে — দ্রুতই টীম যোগাযোগ করবে।",
    "View": "দেখুন",
    "Open": "ওপেন",
    "Replied": "উত্তর দেওয়া হয়েছে",
    "Low": "কম",
    "Medium": "মাঝারি",
    "High": "বেশি",
    "Technical": "প্রযুক্তিগত",
    "Domain": "ডোমেইন",
    "Connect a custom domain": "কাস্টম ডোমেইন কানেক্ট করুন",
    "Point DNS and issue SSL for your store.": "আপনার স্টোরের জন্য DNS পয়েন্ট ও SSL সেটআপ করুন।",
    "Shipping locations": "ডেলিভারি লোকেশন সেটিংস",
    "Zones, rates, and where you deliver.": "ডেলিভারি এলাকা, চার্জ ও ডেলিভারির স্থানসমূহ।",
    "Adding and editing products": "প্রোডাক্ট যোগ ও এডিট করা",
    "Photos, prices, variants, and more.": "ছবি, দাম, ভ্যারিয়েন্ট এবং অন্যান্য তথ্য।",
    "Using the theme editor": "থিম এডিটর ব্যবহার",
    "Brand, colors, pages, and sections.": "ব্র্যান্ড, কালার, পেজ এবং সেকশন পরিবর্তন।",
    "Reading store analytics": "স্টোর অ্যানালিটিক্স দেখা",
    "Sales trends, bestsellers, and exports.": "বিক্রির ট্রেন্ড, সেরা বিক্রি হওয়া প্রোডাক্ট ইত্যাদি।",
    "Managing orders end to end": "সম্পূর্ণ অর্ডার ম্যানেজমেন্ট",
    "Statuses, packing, and customer updates.": "অর্ডার স্ট্যাটাস, প্যাকিং এবং কাস্টমার আপডেট।",
    "Retail store": "রিটেইল শপ / খুচরা দোকান",
    "Online only": "শুধুমাত্র অনলাইন বিজনে্‌স",
    "Hybrid (online + offline)": "অনলাইন + অফলাইন বিজনে্‌স",
    "Wholesale": "পাইকারি / হোলসেল",
    "Service business": "সার্ভিস বিজনে্‌স",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  locale: "bn",
  setLocale: () => {},
  toggleLocale: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("bn");

  useEffect(() => {
    const saved = localStorage.getItem(STORAGE_KEY) as Locale | null;
    if (saved === "en" || saved === "bn") {
      setLocaleState(saved);
    }
  }, []);

  function setLocale(newLocale: Locale) {
    setLocaleState(newLocale);
    localStorage.setItem(STORAGE_KEY, newLocale);
  }

  function toggleLocale() {
    setLocale(locale === "en" ? "bn" : "en");
  }

  function t(key: string): string {
    return DICTIONARY[locale]?.[key] ?? DICTIONARY.en[key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ locale, setLocale, toggleLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
